version: 1.2
workflows:
 - name: GEMSTONE_Isolates_Illumina_PE
   subclass: WDL
   primaryDescriptorPath: /workflows/gemstone/wf_gemstone_isolates.wdl
 - name: Kraken2_Bracken_PE
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_kraken2_pe.wdl
 - name: StrainGE_PE
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_strainge_pe.wdl
 - name: GEMSTONE_Plate_Swipes_Illumina_PE
   subclass: WDL
   primaryDescriptorPath: /workflows/gemstone/wf_gemstone_plate_swipes.wdl
 - name: MetaWRAP_PE
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_metawrap.wdl
 - name: GEMSTONE_QC_flags_table
   subclass: WDL
   primaryDescriptorPath: /workflows/utilities/wf_qc_flags_table.wdl
 - name: GEMSTONE_QC_flags_row
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_qc.wdl
 - name: StrainGST_top_strain
   subclass: WDL
   primaryDescriptorPath: /workflows/utilities/wf_top_strain.wdl
 - name: GEMSTONE_status
   subclass: WDL
   primaryDescriptorPath: /workflows/utilities/wf_status.wdl
 - name: GEMSTONE_StrainGR
   subclass: WDL
   primaryDescriptorPath: /workflows/gemstone/wf_gemstone_straingr.wdl
 - name: StrainGR_prepare
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_straingr_prepare.wdl