#!/bin/bash

VERSION="1.0.0"

cd docker/utils
echo Building the Docker image
docker build -t marcoteix/gemstone-utils:$VERSION .
echo Pushing to Docker Hub
docker push marcoteix/gemstone-utils:$VERSION